[package]
name = "dagger-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
path = "src/macros.rs"

[dependencies]
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["visit"] }

[features]
visualize = []
